[package]
name = "zkemail"
type = "lib"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]
compiler_version = ">=0.33.0"

[dependencies]
noir_rsa = { tag = "v0.2", git = "https://github.com/noir-lang/noir_rsa" }
noir_base64 = { tag = "v0.2.0", git = "https://github.com/noir-lang/noir_base64" }
string_search = { tag = "v0.1", git = "https://github.com/noir-lang/noir_string_search" }
